# https://docs.docker.com/compose/extends/
# This file gets automatically loaded via docker-compose/rancher-compose.
#
# It's used to set local dev specific overrides for volumes and ports.
#
# In local dev we use the docker-compose.override.yml as the override removing ports
# and local volumes bound to the host.
#
# YAML (String|Integer) get replaced/overridden
# YAML Arrays get merged/appended opposed to overridden
version: "2"
services:
  web:
    image: docker-registry.weedmaps.com/admin/nginx:${sha}
    labels:
      io.rancher_activelb.server_names: ${SERVER_NAMES}
      io.rancher.scheduler.global: 'true'
      # sets things up so it responds to admin-acceptance.weedmaps.com and web.admin.acceptance-us-west2.weedmaps.com
      io.rancher_nginxlb.server_names: admin-${deploy_environment}.internal-weedmaps.com,web.admin,admin.internal-weedmaps.com,www.admin-${deploy_environment}.internal-weedmaps.com,www.admin.weedmaps.com,admin.weedmaps.com,admin-${deploy_environment}.weedmaps.com
      io.rancher.sidekicks: app
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      io.rancher_activelb.visibility: ${SERVICE_VISIBILITY}
    environment:
      - NODE_ENV=${APPLICATION_ENVIRONMENT}
      # these add fields and tags in the ELK dashboards for filtering/aggregation
      - LOGSTASH_TAGS=admin,${deploy_environment},nginx,web
      - LOGSTASH_FIELDS=stack=admin,service=web,deploy_environment=${deploy_environment},sha=${sha},application_environment=${application_environment}
    ports:
      - 80
    volumes_from:
      - app
  app:
    image: docker-registry.weedmaps.com/admin/app:${sha}
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
    ports:
      - 1620
    volumes:
      - /var/www/admin/static
      - /var/www/admin/build
    environment:
      - NODE_ENV=${APPLICATION_ENVIRONMENT}
      - DEPLOY_ENVIRONMENT=${deploy_environment}
      # these add fields and tags in the ELK dashboards for filtering/aggregation
      - LOGSTASH_TAGS=admin,${deploy_environment},app
      - LOGSTASH_FIELDS=stack=admin,service=app,deploy_environment=${deploy_environment},sha=${sha},application_environment=${application_environment}
  storybook:
    image: docker-registry.weedmaps.com/admin/storybook:${sha}
    labels:
      io.rancher_activelb.server_names: ${SERVER_NAMES_STORYBOOK}
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
    environment:
      - NODE_ENV=${APPLICATION_ENVIRONMENT}
    ports:
      - 6006
