# https://docs.rancher.com/rancher/v1.4/en/cattle/rancher-compose/
# This file is used to determine scaling, scheduling and load balancing of containers
#
version: '2'
services:
  app:
    start_on_create: true
    upgrade_strategy:
      start_first: true
    health_check:
      request_line: GET /healthz HTTP/1.0
      response_timeout: 2000
      healthy_threshold: 2
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 1620
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 60000
      strategy: recreateOnQuorum
      reinitializing_timeout: 60000
  storybook:
    start_on_create: true
    upgrade_strategy:
      start_first: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreateOnQuorum
      reinitializing_timeout: 60000
