// flow-typed signature: e5f177920e806956dabf23281244d2e6
// flow-typed version: <<STUB>>/bimap_v0.0.15/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bimap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bimap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bimap/lib/bimap' {
  declare module.exports: any;
}

declare module 'bimap/test/browser/chai' {
  declare module.exports: any;
}

declare module 'bimap/test/browser/mocha' {
  declare module.exports: any;
}

declare module 'bimap/test/browser/WebConsole' {
  declare module.exports: any;
}

declare module 'bimap/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bimap/lib/bimap.js' {
  declare module.exports: $Exports<'bimap/lib/bimap'>;
}
declare module 'bimap/test/browser/chai.js' {
  declare module.exports: $Exports<'bimap/test/browser/chai'>;
}
declare module 'bimap/test/browser/mocha.js' {
  declare module.exports: $Exports<'bimap/test/browser/mocha'>;
}
declare module 'bimap/test/browser/WebConsole.js' {
  declare module.exports: $Exports<'bimap/test/browser/WebConsole'>;
}
declare module 'bimap/test/tests.js' {
  declare module.exports: $Exports<'bimap/test/tests'>;
}
