// flow-typed signature: 604bb4d81d481a029d70846fce166ada
// flow-typed version: <<STUB>>/danger-plugin-jira-issue_v^1.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger-plugin-jira-issue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger-plugin-jira-issue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'danger-plugin-jira-issue/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'danger-plugin-jira-issue/dist/index.js' {
  declare module.exports: $Exports<'danger-plugin-jira-issue/dist/index'>;
}
