// flow-typed signature: f3db69b8da433c5d89c141e83e194326
// flow-typed version: <<STUB>>/enzyme-context-patch_v0.0.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-context-patch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-context-patch' {
  declare module.exports: any;
}
