// flow-typed signature: 2a9c2b24cdfc8e434ba43c022db3d86f
// flow-typed version: <<STUB>>/express-csp_v^0.1.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-csp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-csp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-csp/lib/csp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-csp/index' {
  declare module.exports: $Exports<'express-csp'>;
}
declare module 'express-csp/index.js' {
  declare module.exports: $Exports<'express-csp'>;
}
declare module 'express-csp/lib/csp.js' {
  declare module.exports: $Exports<'express-csp/lib/csp'>;
}
