// flow-typed signature: ffd870cf9c9206562df4972a54fafb6a
// flow-typed version: <<STUB>>/hash-files_v~1.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hash-files'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hash-files' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hash-files/lib/hash' {
  declare module.exports: any;
}

declare module 'hash-files/lib/options' {
  declare module.exports: any;
}

declare module 'hash-files/test/hash.tests' {
  declare module.exports: any;
}

declare module 'hash-files/test/jshint/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hash-files/lib/hash.js' {
  declare module.exports: $Exports<'hash-files/lib/hash'>;
}
declare module 'hash-files/lib/options.js' {
  declare module.exports: $Exports<'hash-files/lib/options'>;
}
declare module 'hash-files/test/hash.tests.js' {
  declare module.exports: $Exports<'hash-files/test/hash.tests'>;
}
declare module 'hash-files/test/jshint/reporter.js' {
  declare module.exports: $Exports<'hash-files/test/jshint/reporter'>;
}
