// flow-typed signature: 06be9785073764866c412fb0fa99cc10
// flow-typed version: <<STUB>>/honeybadger_v^1.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'honeybadger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'honeybadger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'honeybadger/lib/backend' {
  declare module.exports: any;
}

declare module 'honeybadger/lib/honeybadger' {
  declare module.exports: any;
}

declare module 'honeybadger/lib/logger' {
  declare module.exports: any;
}

declare module 'honeybadger/lib/middleware' {
  declare module.exports: any;
}

declare module 'honeybadger/lib/notice' {
  declare module.exports: any;
}

declare module 'honeybadger/lib/util' {
  declare module.exports: any;
}

declare module 'honeybadger/test/honeybadger' {
  declare module.exports: any;
}

declare module 'honeybadger/test/logger' {
  declare module.exports: any;
}

declare module 'honeybadger/test/middleware' {
  declare module.exports: any;
}

declare module 'honeybadger/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'honeybadger/lib/backend.js' {
  declare module.exports: $Exports<'honeybadger/lib/backend'>;
}
declare module 'honeybadger/lib/honeybadger.js' {
  declare module.exports: $Exports<'honeybadger/lib/honeybadger'>;
}
declare module 'honeybadger/lib/logger.js' {
  declare module.exports: $Exports<'honeybadger/lib/logger'>;
}
declare module 'honeybadger/lib/middleware.js' {
  declare module.exports: $Exports<'honeybadger/lib/middleware'>;
}
declare module 'honeybadger/lib/notice.js' {
  declare module.exports: $Exports<'honeybadger/lib/notice'>;
}
declare module 'honeybadger/lib/util.js' {
  declare module.exports: $Exports<'honeybadger/lib/util'>;
}
declare module 'honeybadger/test/honeybadger.js' {
  declare module.exports: $Exports<'honeybadger/test/honeybadger'>;
}
declare module 'honeybadger/test/logger.js' {
  declare module.exports: $Exports<'honeybadger/test/logger'>;
}
declare module 'honeybadger/test/middleware.js' {
  declare module.exports: $Exports<'honeybadger/test/middleware'>;
}
declare module 'honeybadger/test/util.js' {
  declare module.exports: $Exports<'honeybadger/test/util'>;
}
