// flow-typed signature: 0e097e03206c323cd5ace243debc54b0
// flow-typed version: <<STUB>>/jest-environment-node-debug_v~2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-node-debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-node-debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-environment-node-debug/index' {
  declare module.exports: $Exports<'jest-environment-node-debug'>;
}
declare module 'jest-environment-node-debug/index.js' {
  declare module.exports: $Exports<'jest-environment-node-debug'>;
}
