// flow-typed signature: 0b00ccd4ec39403c5082e057d45afc6a
// flow-typed version: <<STUB>>/lodash.some_v^4.6.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.some'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.some' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.some/index' {
  declare module.exports: $Exports<'lodash.some'>;
}
declare module 'lodash.some/index.js' {
  declare module.exports: $Exports<'lodash.some'>;
}
