// flow-typed signature: 260df5520c07b1f2dcf2519d37c2f4d5
// flow-typed version: <<STUB>>/react-howler_v^3.7.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-howler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-howler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-howler/lib/howler' {
  declare module.exports: any;
}

declare module 'react-howler/lib/index' {
  declare module.exports: any;
}

declare module 'react-howler/lib/ReactHowler' {
  declare module.exports: any;
}

declare module 'react-howler/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-howler/lib/howler.js' {
  declare module.exports: $Exports<'react-howler/lib/howler'>;
}
declare module 'react-howler/lib/index.js' {
  declare module.exports: $Exports<'react-howler/lib/index'>;
}
declare module 'react-howler/lib/ReactHowler.js' {
  declare module.exports: $Exports<'react-howler/lib/ReactHowler'>;
}
declare module 'react-howler/lib/utils.js' {
  declare module.exports: $Exports<'react-howler/lib/utils'>;
}
