// flow-typed signature: 5f127ce9973d89f73580e284801d722f
// flow-typed version: <<STUB>>/react-css-transition-replace_v^3.0.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-css-transition-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-css-transition-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-css-transition-replace/gulpfile' {
  declare module.exports: any;
}

declare module 'react-css-transition-replace/lib/ReactCSSTransitionReplace' {
  declare module.exports: any;
}

declare module 'react-css-transition-replace/lib/ReactCSSTransitionReplaceChild' {
  declare module.exports: any;
}

declare module 'react-css-transition-replace/lib/utils/PropTypes' {
  declare module.exports: any;
}

declare module 'react-css-transition-replace/src/ReactCSSTransitionReplace' {
  declare module.exports: any;
}

declare module 'react-css-transition-replace/src/ReactCSSTransitionReplaceChild' {
  declare module.exports: any;
}

declare module 'react-css-transition-replace/src/utils/PropTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-css-transition-replace/gulpfile.js' {
  declare module.exports: $Exports<'react-css-transition-replace/gulpfile'>;
}
declare module 'react-css-transition-replace/index' {
  declare module.exports: $Exports<'react-css-transition-replace'>;
}
declare module 'react-css-transition-replace/index.js' {
  declare module.exports: $Exports<'react-css-transition-replace'>;
}
declare module 'react-css-transition-replace/lib/ReactCSSTransitionReplace.js' {
  declare module.exports: $Exports<'react-css-transition-replace/lib/ReactCSSTransitionReplace'>;
}
declare module 'react-css-transition-replace/lib/ReactCSSTransitionReplaceChild.js' {
  declare module.exports: $Exports<'react-css-transition-replace/lib/ReactCSSTransitionReplaceChild'>;
}
declare module 'react-css-transition-replace/lib/utils/PropTypes.js' {
  declare module.exports: $Exports<'react-css-transition-replace/lib/utils/PropTypes'>;
}
declare module 'react-css-transition-replace/src/ReactCSSTransitionReplace.jsx' {
  declare module.exports: $Exports<'react-css-transition-replace/src/ReactCSSTransitionReplace'>;
}
declare module 'react-css-transition-replace/src/ReactCSSTransitionReplaceChild.js' {
  declare module.exports: $Exports<'react-css-transition-replace/src/ReactCSSTransitionReplaceChild'>;
}
declare module 'react-css-transition-replace/src/utils/PropTypes.js' {
  declare module.exports: $Exports<'react-css-transition-replace/src/utils/PropTypes'>;
}
