// flow-typed signature: 6ca6b2573f0a34fc42a631fded522bf5
// flow-typed version: <<STUB>>/react-amplitude_v^0.1.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-amplitude'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-amplitude' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-amplitude/dist/index' {
  declare module.exports: any;
}

declare module 'react-amplitude/src/index' {
  declare module.exports: any;
}

declare module 'react-amplitude/src/utils/console' {
  declare module.exports: any;
}

declare module 'react-amplitude/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-amplitude/dist/index.js' {
  declare module.exports: $Exports<'react-amplitude/dist/index'>;
}
declare module 'react-amplitude/src/index.js' {
  declare module.exports: $Exports<'react-amplitude/src/index'>;
}
declare module 'react-amplitude/src/utils/console.js' {
  declare module.exports: $Exports<'react-amplitude/src/utils/console'>;
}
declare module 'react-amplitude/webpack.config.js' {
  declare module.exports: $Exports<'react-amplitude/webpack.config'>;
}
