// flow-typed signature: 71ffc285e41f12668cbb501e8ccf0316
// flow-typed version: <<STUB>>/titleize_v^1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'titleize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'titleize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'titleize/index' {
  declare module.exports: $Exports<'titleize'>;
}
declare module 'titleize/index.js' {
  declare module.exports: $Exports<'titleize'>;
}
