// flow-typed signature: 4684a7618d78d99a6d69e601bc9573da
// flow-typed version: <<STUB>>/@ghostgroup/danger-plugins_v^1.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ghostgroup/danger-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ghostgroup/danger-plugins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ghostgroup/danger-plugins/dist/big-pr' {
  declare module.exports: any;
}

declare module '@ghostgroup/danger-plugins/dist/big-pr.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/danger-plugins/dist/big-snapshots' {
  declare module.exports: any;
}

declare module '@ghostgroup/danger-plugins/dist/big-snapshots.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/danger-plugins/dist/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/danger-plugins/dist/index.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/danger-plugins/dist/library-export' {
  declare module.exports: any;
}

declare module '@ghostgroup/danger-plugins/dist/library-export.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ghostgroup/danger-plugins/dist/big-pr.js' {
  declare module.exports: $Exports<'@ghostgroup/danger-plugins/dist/big-pr'>;
}
declare module '@ghostgroup/danger-plugins/dist/big-pr.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/danger-plugins/dist/big-pr.test',
  >;
}
declare module '@ghostgroup/danger-plugins/dist/big-snapshots.js' {
  declare module.exports: $Exports<
    '@ghostgroup/danger-plugins/dist/big-snapshots',
  >;
}
declare module '@ghostgroup/danger-plugins/dist/big-snapshots.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/danger-plugins/dist/big-snapshots.test',
  >;
}
declare module '@ghostgroup/danger-plugins/dist/index.js' {
  declare module.exports: $Exports<'@ghostgroup/danger-plugins/dist/index'>;
}
declare module '@ghostgroup/danger-plugins/dist/index.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/danger-plugins/dist/index.test',
  >;
}
declare module '@ghostgroup/danger-plugins/dist/library-export.js' {
  declare module.exports: $Exports<
    '@ghostgroup/danger-plugins/dist/library-export',
  >;
}
declare module '@ghostgroup/danger-plugins/dist/library-export.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/danger-plugins/dist/library-export.test',
  >;
}
