// flow-typed signature: 044e87a7c66972be618db9231f6fae81
// flow-typed version: <<STUB>>/@ghostgroup/eslint-config-react_v^1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ghostgroup/eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ghostgroup/eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ghostgroup/eslint-config-react/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ghostgroup/eslint-config-react/test.js' {
  declare module.exports: $Exports<'@ghostgroup/eslint-config-react/test'>;
}
