// flow-typed signature: aee5d432de2801b4247a9744dfbbb220
// flow-typed version: <<STUB>>/@ghostgroup/grid-styled_v~4.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ghostgroup/grid-styled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ghostgroup/grid-styled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ghostgroup/grid-styled/dist/box' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/flex' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/golden' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/grid' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/half' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/inline-box' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/item-grid' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/prop-types' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/quarter' {
  declare module.exports: any;
}

declare module '@ghostgroup/grid-styled/dist/third' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ghostgroup/grid-styled/dist/box.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/box'>;
}
declare module '@ghostgroup/grid-styled/dist/flex.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/flex'>;
}
declare module '@ghostgroup/grid-styled/dist/golden.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/golden'>;
}
declare module '@ghostgroup/grid-styled/dist/grid.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/grid'>;
}
declare module '@ghostgroup/grid-styled/dist/half.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/half'>;
}
declare module '@ghostgroup/grid-styled/dist/index.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/index'>;
}
declare module '@ghostgroup/grid-styled/dist/inline-box.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/inline-box'>;
}
declare module '@ghostgroup/grid-styled/dist/item-grid.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/item-grid'>;
}
declare module '@ghostgroup/grid-styled/dist/prop-types.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/prop-types'>;
}
declare module '@ghostgroup/grid-styled/dist/quarter.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/quarter'>;
}
declare module '@ghostgroup/grid-styled/dist/third.js' {
  declare module.exports: $Exports<'@ghostgroup/grid-styled/dist/third'>;
}
