// flow-typed signature: 4d1843679ab25d437815e854bb538edf
// flow-typed version: <<STUB>>/@ghostgroup/moonshot-cli_v^1.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ghostgroup/moonshot-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ghostgroup/moonshot-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ghostgroup/moonshot-cli/commands/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/commands/make/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/commands/make/make-component' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/commands/make/make-style' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/configs' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/component/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/component/stateful-index-with-styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/component/stateful-index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/component/stateless-index-with-styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/component/stateless-index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/component/stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/component/styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/component/test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/index.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/styled-component/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/styled-component/styled-component' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/styled-component/styled-components-index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/templates/styled-component/styled-import' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/__mocks__/fs' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/__mocks__/writefile' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/component-naming' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/component-naming.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/confirm-tree' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/confirm-tree.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/features' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/features.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/files' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/files.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/filter-md-files' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/filter-md-files.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/find-component' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/find-component.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/get-components' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/get-components.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/is-moonshot-project' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/is-moonshot-project.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/is-unique' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/is-unique.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/split-component' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/split-component.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/template' {
  declare module.exports: any;
}

declare module '@ghostgroup/moonshot-cli/utils/template.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ghostgroup/moonshot-cli/commands/index.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/commands/index'>;
}
declare module '@ghostgroup/moonshot-cli/commands/make/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/commands/make/index',
  >;
}
declare module '@ghostgroup/moonshot-cli/commands/make/make-component.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/commands/make/make-component',
  >;
}
declare module '@ghostgroup/moonshot-cli/commands/make/make-style.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/commands/make/make-style',
  >;
}
declare module '@ghostgroup/moonshot-cli/configs.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/configs'>;
}
declare module '@ghostgroup/moonshot-cli/index' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli'>;
}
declare module '@ghostgroup/moonshot-cli/index.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli'>;
}
declare module '@ghostgroup/moonshot-cli/templates/component/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/component/index',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/component/stateful-index-with-styles.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/component/stateful-index-with-styles',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/component/stateful-index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/component/stateful-index',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/component/stateless-index-with-styles.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/component/stateless-index-with-styles',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/component/stateless-index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/component/stateless-index',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/component/stories.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/component/stories',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/component/styles.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/component/styles',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/component/test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/component/test',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/index.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/templates/index'>;
}
declare module '@ghostgroup/moonshot-cli/templates/index.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/index.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/styled-component/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/styled-component/index',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/styled-component/styled-component.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/styled-component/styled-component',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/styled-component/styled-components-index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/styled-component/styled-components-index',
  >;
}
declare module '@ghostgroup/moonshot-cli/templates/styled-component/styled-import.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/templates/styled-component/styled-import',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/__mocks__/fs.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/__mocks__/fs',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/__mocks__/writefile.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/__mocks__/writefile',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/component-naming.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/component-naming',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/component-naming.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/component-naming.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/confirm-tree.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/confirm-tree',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/confirm-tree.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/confirm-tree.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/features.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/utils/features'>;
}
declare module '@ghostgroup/moonshot-cli/utils/features.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/features.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/files.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/utils/files'>;
}
declare module '@ghostgroup/moonshot-cli/utils/files.test.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/utils/files.test'>;
}
declare module '@ghostgroup/moonshot-cli/utils/filter-md-files.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/filter-md-files',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/filter-md-files.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/filter-md-files.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/find-component.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/find-component',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/find-component.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/find-component.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/get-components.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/get-components',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/get-components.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/get-components.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/index.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/utils/index'>;
}
declare module '@ghostgroup/moonshot-cli/utils/is-moonshot-project.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/is-moonshot-project',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/is-moonshot-project.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/is-moonshot-project.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/is-unique.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/utils/is-unique'>;
}
declare module '@ghostgroup/moonshot-cli/utils/is-unique.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/is-unique.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/split-component.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/split-component',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/split-component.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/split-component.test',
  >;
}
declare module '@ghostgroup/moonshot-cli/utils/template.js' {
  declare module.exports: $Exports<'@ghostgroup/moonshot-cli/utils/template'>;
}
declare module '@ghostgroup/moonshot-cli/utils/template.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/moonshot-cli/utils/template.test',
  >;
}
