// flow-typed signature: 62a86cae87f8e7d24d348a1afa359a0b
// flow-typed version: <<STUB>>/@ghostgroup/puffpuff_v^3.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ghostgroup/puffpuff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ghostgroup/puffpuff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ghostgroup/puffpuff/dist/index.cjs' {
  declare module.exports: any;
}

declare module '@ghostgroup/puffpuff/dist/index.esm' {
  declare module.exports: any;
}

declare module '@ghostgroup/puffpuff/src/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/puffpuff/src/puffpuff/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/puffpuff/src/react/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ghostgroup/puffpuff/dist/index.cjs.js' {
  declare module.exports: $Exports<'@ghostgroup/puffpuff/dist/index.cjs'>;
}
declare module '@ghostgroup/puffpuff/dist/index.esm.js' {
  declare module.exports: $Exports<'@ghostgroup/puffpuff/dist/index.esm'>;
}
declare module '@ghostgroup/puffpuff/src/index.js' {
  declare module.exports: $Exports<'@ghostgroup/puffpuff/src/index'>;
}
declare module '@ghostgroup/puffpuff/src/puffpuff/index.js' {
  declare module.exports: $Exports<'@ghostgroup/puffpuff/src/puffpuff/index'>;
}
declare module '@ghostgroup/puffpuff/src/react/index.js' {
  declare module.exports: $Exports<'@ghostgroup/puffpuff/src/react/index'>;
}
