// flow-typed signature: 76c4de9b3389e03170d174ce7b32d592
// flow-typed version: <<STUB>>/@ghostgroup/ui_v^16.0.10/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ghostgroup/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ghostgroup/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ghostgroup/ui/dist/index.cjs' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/dist/index.esm' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/analytics/amplitude' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/analytics/amplitude.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/analytics/analytics.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/analytics/analytics.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/analytics/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/animated-stars/animated-stars.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/animated-stars/animated-stars.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/animated-stars/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/autosizer/autosizer.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/autosizer/autosizer.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/autosizer/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/button-group/button-group.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/button-group/button-group.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/button-group/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/button/button.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/button/button.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/button/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/card/card.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/card/card.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/card/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/combo-select/combo-select.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/combo-select/combo-select.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/combo-select/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/combo-select/styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/constants/colors' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/constants/depths' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/constants/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/constants/story-theme' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/expandable/expandable-content' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/expandable/expandable' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/expandable/expandable.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/expandable/expandable.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/expandable/expandable.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/expandable/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/expandable/story-components/dynamic-list' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/hide/hide.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/hide/hide.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/hide/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/arrow' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/check' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/close' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/filter-lines' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/filter' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/icon-wrapper.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/icons.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/icons.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/info' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/listings' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/minus' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/pagination-arrow' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/phone' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/plus' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/search' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/sort-lines' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/spinner' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/star-half' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/star-o' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/star' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/trash' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/icons/verified' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/index.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/infinite-scroller/examples' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/infinite-scroller/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/infinite-scroller/infinite-scroller.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/infinite-scroller/infinite-scroller.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/infinite-scroller/styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/interactive-stars/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/interactive-stars/interactive-stars.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/interactive-stars/interactive-stars.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/interactive-stars/styled-components/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/jukebox/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/jukebox/jukebox.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/jukebox/jukebox.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/lib/common/noop' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/lib/common/noop.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/lib/common/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/logos/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/logos/logos.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/logos/logos.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/logos/wm-logo-mini-inverse' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/logos/wm-logo-mini' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/logos/wm-logo' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/multi-select.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/multi-select.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/remove-button' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/styled-components/dropdown-button.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/styled-components/dropdown.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/styled-components/icons.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/styled-components/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/styled-components/input.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/styled-components/item.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/multi-select/styled-components/selected-pill.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/paging-controls/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/paging-controls/paging-controls.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/paging-controls/paging-controls.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/replacer/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/replacer/replacer.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/replacer/replacer.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/replacer/styled-components/cross-fade.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/replacer/styled-components/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/replacer/styled-components/roll-up.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/replacer/styled-components/translate.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/select/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/select/select.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/select/select.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/select/styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/app-header' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/app-info' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/mock-side-nav' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/side-nav-layout' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/side-nav-link-child' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/side-nav-link' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/side-nav.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/side-nav.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/side-nav/styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/site-header/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/site-header/site-header.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/site-header/site-header.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/stars/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/stars/stars.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/stars/stars.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/static-map/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/static-map/spherical-mercator' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/static-map/static-map.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/static-map/static-map.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/static-map/styled-components/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/swipe-events/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/swipe-events/swipe-events.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/swipe-events/swipe-events.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/__mocks__/react-resize-detector' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/constants' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/story-components/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/story-components/responsive-desktop-wrapper.component' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/story-components/selector.component' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/styled-components/active-tab-wrapper.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/styled-components/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/styled-components/selection-indicator-bar.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/styled-components/tab-wrapper.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/styled-components/tabs-wrapper.styled' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/tab.component' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/tabs.component' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/tabs.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/tabs/tabs.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/temporary-message/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/temporary-message/story-components/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/temporary-message/story-components/temporary-message-stretch-with-button.component' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/temporary-message/story-components/temporary-message-with-button.component' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/temporary-message/temporary-message.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/temporary-message/temporary-message.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/text-limit-textbox/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/text-limit-textbox/story-components/demo-limit-textbox' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/text-limit-textbox/story-components/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/text-limit-textbox/styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/text-limit-textbox/text-limit-box.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/text-limit-textbox/text-limit-box.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/theme/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/theme/theme.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/timer/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/timer/simple-timer' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/timer/simple-timer.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/timer/timer.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/toggle/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/toggle/styles' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/toggle/toggle.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/toggle/toggle.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/touchable/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/touchable/touchable.stories' {
  declare module.exports: any;
}

declare module '@ghostgroup/ui/src/touchable/touchable.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ghostgroup/ui/dist/index.cjs.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/dist/index.cjs'>;
}
declare module '@ghostgroup/ui/dist/index.esm.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/dist/index.esm'>;
}
declare module '@ghostgroup/ui/src/analytics/amplitude.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/analytics/amplitude'>;
}
declare module '@ghostgroup/ui/src/analytics/amplitude.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/analytics/amplitude.test'>;
}
declare module '@ghostgroup/ui/src/analytics/analytics.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/analytics/analytics.stories'>;
}
declare module '@ghostgroup/ui/src/analytics/analytics.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/analytics/analytics.test'>;
}
declare module '@ghostgroup/ui/src/analytics/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/analytics/index'>;
}
declare module '@ghostgroup/ui/src/animated-stars/animated-stars.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/animated-stars/animated-stars.stories'>;
}
declare module '@ghostgroup/ui/src/animated-stars/animated-stars.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/animated-stars/animated-stars.test'>;
}
declare module '@ghostgroup/ui/src/animated-stars/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/animated-stars/index'>;
}
declare module '@ghostgroup/ui/src/autosizer/autosizer.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/autosizer/autosizer.stories'>;
}
declare module '@ghostgroup/ui/src/autosizer/autosizer.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/autosizer/autosizer.test'>;
}
declare module '@ghostgroup/ui/src/autosizer/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/autosizer/index'>;
}
declare module '@ghostgroup/ui/src/button-group/button-group.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/button-group/button-group.stories'>;
}
declare module '@ghostgroup/ui/src/button-group/button-group.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/button-group/button-group.test'>;
}
declare module '@ghostgroup/ui/src/button-group/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/button-group/index'>;
}
declare module '@ghostgroup/ui/src/button/button.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/button/button.stories'>;
}
declare module '@ghostgroup/ui/src/button/button.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/button/button.test'>;
}
declare module '@ghostgroup/ui/src/button/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/button/index'>;
}
declare module '@ghostgroup/ui/src/card/card.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/card/card.stories'>;
}
declare module '@ghostgroup/ui/src/card/card.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/card/card.test'>;
}
declare module '@ghostgroup/ui/src/card/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/card/index'>;
}
declare module '@ghostgroup/ui/src/combo-select/combo-select.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/combo-select/combo-select.stories'>;
}
declare module '@ghostgroup/ui/src/combo-select/combo-select.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/combo-select/combo-select.test'>;
}
declare module '@ghostgroup/ui/src/combo-select/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/combo-select/index'>;
}
declare module '@ghostgroup/ui/src/combo-select/styles.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/combo-select/styles'>;
}
declare module '@ghostgroup/ui/src/constants/colors.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/constants/colors'>;
}
declare module '@ghostgroup/ui/src/constants/depths.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/constants/depths'>;
}
declare module '@ghostgroup/ui/src/constants/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/constants/index'>;
}
declare module '@ghostgroup/ui/src/constants/story-theme.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/constants/story-theme'>;
}
declare module '@ghostgroup/ui/src/expandable/expandable-content.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/expandable/expandable-content'>;
}
declare module '@ghostgroup/ui/src/expandable/expandable.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/expandable/expandable'>;
}
declare module '@ghostgroup/ui/src/expandable/expandable.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/expandable/expandable.stories'>;
}
declare module '@ghostgroup/ui/src/expandable/expandable.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/expandable/expandable.styled'>;
}
declare module '@ghostgroup/ui/src/expandable/expandable.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/expandable/expandable.test'>;
}
declare module '@ghostgroup/ui/src/expandable/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/expandable/index'>;
}
declare module '@ghostgroup/ui/src/expandable/story-components/dynamic-list.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/expandable/story-components/dynamic-list'>;
}
declare module '@ghostgroup/ui/src/hide/hide.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/hide/hide.stories'>;
}
declare module '@ghostgroup/ui/src/hide/hide.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/hide/hide.test'>;
}
declare module '@ghostgroup/ui/src/hide/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/hide/index'>;
}
declare module '@ghostgroup/ui/src/icons/arrow.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/arrow'>;
}
declare module '@ghostgroup/ui/src/icons/check.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/check'>;
}
declare module '@ghostgroup/ui/src/icons/close.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/close'>;
}
declare module '@ghostgroup/ui/src/icons/filter-lines.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/filter-lines'>;
}
declare module '@ghostgroup/ui/src/icons/filter.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/filter'>;
}
declare module '@ghostgroup/ui/src/icons/icon-wrapper.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/icon-wrapper.styled'>;
}
declare module '@ghostgroup/ui/src/icons/icons.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/icons.stories'>;
}
declare module '@ghostgroup/ui/src/icons/icons.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/icons.test'>;
}
declare module '@ghostgroup/ui/src/icons/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/index'>;
}
declare module '@ghostgroup/ui/src/icons/info.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/info'>;
}
declare module '@ghostgroup/ui/src/icons/listings.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/listings'>;
}
declare module '@ghostgroup/ui/src/icons/minus.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/minus'>;
}
declare module '@ghostgroup/ui/src/icons/pagination-arrow.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/pagination-arrow'>;
}
declare module '@ghostgroup/ui/src/icons/phone.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/phone'>;
}
declare module '@ghostgroup/ui/src/icons/plus.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/plus'>;
}
declare module '@ghostgroup/ui/src/icons/search.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/search'>;
}
declare module '@ghostgroup/ui/src/icons/sort-lines.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/sort-lines'>;
}
declare module '@ghostgroup/ui/src/icons/spinner.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/spinner'>;
}
declare module '@ghostgroup/ui/src/icons/star-half.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/star-half'>;
}
declare module '@ghostgroup/ui/src/icons/star-o.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/star-o'>;
}
declare module '@ghostgroup/ui/src/icons/star.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/star'>;
}
declare module '@ghostgroup/ui/src/icons/trash.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/trash'>;
}
declare module '@ghostgroup/ui/src/icons/verified.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/icons/verified'>;
}
declare module '@ghostgroup/ui/src/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/index'>;
}
declare module '@ghostgroup/ui/src/index.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/index.test'>;
}
declare module '@ghostgroup/ui/src/infinite-scroller/examples.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/infinite-scroller/examples'>;
}
declare module '@ghostgroup/ui/src/infinite-scroller/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/infinite-scroller/index'>;
}
declare module '@ghostgroup/ui/src/infinite-scroller/infinite-scroller.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/infinite-scroller/infinite-scroller.stories'>;
}
declare module '@ghostgroup/ui/src/infinite-scroller/infinite-scroller.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/infinite-scroller/infinite-scroller.test'>;
}
declare module '@ghostgroup/ui/src/infinite-scroller/styles.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/infinite-scroller/styles'>;
}
declare module '@ghostgroup/ui/src/interactive-stars/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/interactive-stars/index'>;
}
declare module '@ghostgroup/ui/src/interactive-stars/interactive-stars.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/interactive-stars/interactive-stars.stories'>;
}
declare module '@ghostgroup/ui/src/interactive-stars/interactive-stars.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/interactive-stars/interactive-stars.test'>;
}
declare module '@ghostgroup/ui/src/interactive-stars/styled-components/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/interactive-stars/styled-components/index'>;
}
declare module '@ghostgroup/ui/src/jukebox/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/jukebox/index'>;
}
declare module '@ghostgroup/ui/src/jukebox/jukebox.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/jukebox/jukebox.stories'>;
}
declare module '@ghostgroup/ui/src/jukebox/jukebox.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/jukebox/jukebox.test'>;
}
declare module '@ghostgroup/ui/src/lib/common/noop.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/lib/common/noop'>;
}
declare module '@ghostgroup/ui/src/lib/common/noop.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/lib/common/noop.test'>;
}
declare module '@ghostgroup/ui/src/lib/common/types.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/lib/common/types'>;
}
declare module '@ghostgroup/ui/src/logos/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/logos/index'>;
}
declare module '@ghostgroup/ui/src/logos/logos.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/logos/logos.stories'>;
}
declare module '@ghostgroup/ui/src/logos/logos.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/logos/logos.test'>;
}
declare module '@ghostgroup/ui/src/logos/wm-logo-mini-inverse.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/logos/wm-logo-mini-inverse'>;
}
declare module '@ghostgroup/ui/src/logos/wm-logo-mini.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/logos/wm-logo-mini'>;
}
declare module '@ghostgroup/ui/src/logos/wm-logo.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/logos/wm-logo'>;
}
declare module '@ghostgroup/ui/src/multi-select/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/index'>;
}
declare module '@ghostgroup/ui/src/multi-select/multi-select.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/multi-select.stories'>;
}
declare module '@ghostgroup/ui/src/multi-select/multi-select.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/multi-select.test'>;
}
declare module '@ghostgroup/ui/src/multi-select/remove-button.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/remove-button'>;
}
declare module '@ghostgroup/ui/src/multi-select/styled-components/dropdown-button.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/styled-components/dropdown-button.styled'>;
}
declare module '@ghostgroup/ui/src/multi-select/styled-components/dropdown.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/styled-components/dropdown.styled'>;
}
declare module '@ghostgroup/ui/src/multi-select/styled-components/icons.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/styled-components/icons.styled'>;
}
declare module '@ghostgroup/ui/src/multi-select/styled-components/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/styled-components/index'>;
}
declare module '@ghostgroup/ui/src/multi-select/styled-components/input.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/styled-components/input.styled'>;
}
declare module '@ghostgroup/ui/src/multi-select/styled-components/item.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/styled-components/item.styled'>;
}
declare module '@ghostgroup/ui/src/multi-select/styled-components/selected-pill.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/multi-select/styled-components/selected-pill.styled'>;
}
declare module '@ghostgroup/ui/src/paging-controls/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/paging-controls/index'>;
}
declare module '@ghostgroup/ui/src/paging-controls/paging-controls.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/paging-controls/paging-controls.stories'>;
}
declare module '@ghostgroup/ui/src/paging-controls/paging-controls.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/paging-controls/paging-controls.test'>;
}
declare module '@ghostgroup/ui/src/replacer/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/replacer/index'>;
}
declare module '@ghostgroup/ui/src/replacer/replacer.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/replacer/replacer.stories'>;
}
declare module '@ghostgroup/ui/src/replacer/replacer.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/replacer/replacer.test'>;
}
declare module '@ghostgroup/ui/src/replacer/styled-components/cross-fade.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/replacer/styled-components/cross-fade.styled'>;
}
declare module '@ghostgroup/ui/src/replacer/styled-components/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/replacer/styled-components/index'>;
}
declare module '@ghostgroup/ui/src/replacer/styled-components/roll-up.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/replacer/styled-components/roll-up.styled'>;
}
declare module '@ghostgroup/ui/src/replacer/styled-components/translate.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/replacer/styled-components/translate.styled'>;
}
declare module '@ghostgroup/ui/src/select/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/select/index'>;
}
declare module '@ghostgroup/ui/src/select/select.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/select/select.stories'>;
}
declare module '@ghostgroup/ui/src/select/select.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/select/select.test'>;
}
declare module '@ghostgroup/ui/src/select/styles.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/select/styles'>;
}
declare module '@ghostgroup/ui/src/side-nav/app-header.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/app-header'>;
}
declare module '@ghostgroup/ui/src/side-nav/app-info.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/app-info'>;
}
declare module '@ghostgroup/ui/src/side-nav/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/index'>;
}
declare module '@ghostgroup/ui/src/side-nav/mock-side-nav.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/mock-side-nav'>;
}
declare module '@ghostgroup/ui/src/side-nav/side-nav-layout.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/side-nav-layout'>;
}
declare module '@ghostgroup/ui/src/side-nav/side-nav-link-child.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/side-nav-link-child'>;
}
declare module '@ghostgroup/ui/src/side-nav/side-nav-link.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/side-nav-link'>;
}
declare module '@ghostgroup/ui/src/side-nav/side-nav.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/side-nav.stories'>;
}
declare module '@ghostgroup/ui/src/side-nav/side-nav.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/side-nav.test'>;
}
declare module '@ghostgroup/ui/src/side-nav/styles.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/side-nav/styles'>;
}
declare module '@ghostgroup/ui/src/site-header/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/site-header/index'>;
}
declare module '@ghostgroup/ui/src/site-header/site-header.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/site-header/site-header.stories'>;
}
declare module '@ghostgroup/ui/src/site-header/site-header.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/site-header/site-header.test'>;
}
declare module '@ghostgroup/ui/src/stars/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/stars/index'>;
}
declare module '@ghostgroup/ui/src/stars/stars.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/stars/stars.stories'>;
}
declare module '@ghostgroup/ui/src/stars/stars.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/stars/stars.test'>;
}
declare module '@ghostgroup/ui/src/static-map/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/static-map/index'>;
}
declare module '@ghostgroup/ui/src/static-map/spherical-mercator.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/static-map/spherical-mercator'>;
}
declare module '@ghostgroup/ui/src/static-map/static-map.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/static-map/static-map.stories'>;
}
declare module '@ghostgroup/ui/src/static-map/static-map.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/static-map/static-map.test'>;
}
declare module '@ghostgroup/ui/src/static-map/styled-components/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/static-map/styled-components/index'>;
}
declare module '@ghostgroup/ui/src/swipe-events/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/swipe-events/index'>;
}
declare module '@ghostgroup/ui/src/swipe-events/swipe-events.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/swipe-events/swipe-events.stories'>;
}
declare module '@ghostgroup/ui/src/swipe-events/swipe-events.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/swipe-events/swipe-events.test'>;
}
declare module '@ghostgroup/ui/src/tabs/__mocks__/react-resize-detector.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/__mocks__/react-resize-detector'>;
}
declare module '@ghostgroup/ui/src/tabs/constants.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/constants'>;
}
declare module '@ghostgroup/ui/src/tabs/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/index'>;
}
declare module '@ghostgroup/ui/src/tabs/story-components/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/story-components/index'>;
}
declare module '@ghostgroup/ui/src/tabs/story-components/responsive-desktop-wrapper.component.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/story-components/responsive-desktop-wrapper.component'>;
}
declare module '@ghostgroup/ui/src/tabs/story-components/selector.component.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/story-components/selector.component'>;
}
declare module '@ghostgroup/ui/src/tabs/styled-components/active-tab-wrapper.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/styled-components/active-tab-wrapper.styled'>;
}
declare module '@ghostgroup/ui/src/tabs/styled-components/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/styled-components/index'>;
}
declare module '@ghostgroup/ui/src/tabs/styled-components/selection-indicator-bar.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/styled-components/selection-indicator-bar.styled'>;
}
declare module '@ghostgroup/ui/src/tabs/styled-components/tab-wrapper.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/styled-components/tab-wrapper.styled'>;
}
declare module '@ghostgroup/ui/src/tabs/styled-components/tabs-wrapper.styled.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/styled-components/tabs-wrapper.styled'>;
}
declare module '@ghostgroup/ui/src/tabs/tab.component.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/tab.component'>;
}
declare module '@ghostgroup/ui/src/tabs/tabs.component.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/tabs.component'>;
}
declare module '@ghostgroup/ui/src/tabs/tabs.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/tabs.stories'>;
}
declare module '@ghostgroup/ui/src/tabs/tabs.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/tabs/tabs.test'>;
}
declare module '@ghostgroup/ui/src/temporary-message/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/temporary-message/index'>;
}
declare module '@ghostgroup/ui/src/temporary-message/story-components/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/temporary-message/story-components/index'>;
}
declare module '@ghostgroup/ui/src/temporary-message/story-components/temporary-message-stretch-with-button.component.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/temporary-message/story-components/temporary-message-stretch-with-button.component'>;
}
declare module '@ghostgroup/ui/src/temporary-message/story-components/temporary-message-with-button.component.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/temporary-message/story-components/temporary-message-with-button.component'>;
}
declare module '@ghostgroup/ui/src/temporary-message/temporary-message.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/temporary-message/temporary-message.stories'>;
}
declare module '@ghostgroup/ui/src/temporary-message/temporary-message.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/temporary-message/temporary-message.test'>;
}
declare module '@ghostgroup/ui/src/text-limit-textbox/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/text-limit-textbox/index'>;
}
declare module '@ghostgroup/ui/src/text-limit-textbox/story-components/demo-limit-textbox.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/text-limit-textbox/story-components/demo-limit-textbox'>;
}
declare module '@ghostgroup/ui/src/text-limit-textbox/story-components/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/text-limit-textbox/story-components/index'>;
}
declare module '@ghostgroup/ui/src/text-limit-textbox/styles.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/text-limit-textbox/styles'>;
}
declare module '@ghostgroup/ui/src/text-limit-textbox/text-limit-box.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/text-limit-textbox/text-limit-box.stories'>;
}
declare module '@ghostgroup/ui/src/text-limit-textbox/text-limit-box.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/text-limit-textbox/text-limit-box.test'>;
}
declare module '@ghostgroup/ui/src/theme/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/theme/index'>;
}
declare module '@ghostgroup/ui/src/theme/theme.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/theme/theme.test'>;
}
declare module '@ghostgroup/ui/src/timer/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/timer/index'>;
}
declare module '@ghostgroup/ui/src/timer/simple-timer.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/timer/simple-timer'>;
}
declare module '@ghostgroup/ui/src/timer/simple-timer.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/timer/simple-timer.test'>;
}
declare module '@ghostgroup/ui/src/timer/timer.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/timer/timer.test'>;
}
declare module '@ghostgroup/ui/src/toggle/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/toggle/index'>;
}
declare module '@ghostgroup/ui/src/toggle/styles.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/toggle/styles'>;
}
declare module '@ghostgroup/ui/src/toggle/toggle.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/toggle/toggle.stories'>;
}
declare module '@ghostgroup/ui/src/toggle/toggle.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/toggle/toggle.test'>;
}
declare module '@ghostgroup/ui/src/touchable/index.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/touchable/index'>;
}
declare module '@ghostgroup/ui/src/touchable/touchable.stories.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/touchable/touchable.stories'>;
}
declare module '@ghostgroup/ui/src/touchable/touchable.test.js' {
  declare module.exports: $Exports<'@ghostgroup/ui/src/touchable/touchable.test'>;
}
