// flow-typed signature: 0e75d69a7dc3940a0470f1b0c44243f6
// flow-typed version: <<STUB>>/@ghostgroup/wm-sdk-js_v^1.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ghostgroup/wm-sdk-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ghostgroup/wm-sdk-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ghostgroup/wm-sdk-js/dist/index.cjs' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/index.esm' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/auth.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/cookie' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/mocks' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/browser' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/express' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/index.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/favorites.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/geo.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/listings/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/logistics.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/reviews.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/url/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/url/url.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/user-profile.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user/index' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user/user.test' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/response/types' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/wm-sdk' {
  declare module.exports: any;
}

declare module '@ghostgroup/wm-sdk-js/dist/lib/wm-sdk.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ghostgroup/wm-sdk-js/dist/index.cjs.js' {
  declare module.exports: $Exports<'@ghostgroup/wm-sdk-js/dist/index.cjs'>;
}
declare module '@ghostgroup/wm-sdk-js/dist/index.esm.js' {
  declare module.exports: $Exports<'@ghostgroup/wm-sdk-js/dist/index.esm'>;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/auth.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/auth.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/cookie.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/cookie',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/mocks.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/mocks',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/browser.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/browser',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/express.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/express',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/index.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/storage/index.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/auth/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/favorites.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/favorites.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/favorites/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/geo.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/geo.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/geo/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/listings/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/listings/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/logistics.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/logistics.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/logistics/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/reviews.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/reviews.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/reviews/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/url/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/url/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/url/url.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/url/url.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/user-profile.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/user-profile/user-profile.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user/index.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/user/index',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/user/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/modules/user/user.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/modules/user/user.test',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/response/types.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/response/types',
  >;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/wm-sdk.js' {
  declare module.exports: $Exports<'@ghostgroup/wm-sdk-js/dist/lib/wm-sdk'>;
}
declare module '@ghostgroup/wm-sdk-js/dist/lib/wm-sdk.test.js' {
  declare module.exports: $Exports<
    '@ghostgroup/wm-sdk-js/dist/lib/wm-sdk.test',
  >;
}
