#!/bin/bash
# Please add *.dec to your .gitignore/.chefignore
# This script assumes your decrypted file ends with the .dec suffix
# crypto -e secret_file takes secret_file.dec and encrypts it to secret_file
# crypto -d secret_file takes secret_file and decrypts it to secret_file.dec
FLAG=$1
FILE=$2


case $1 in
    -e )
      openssl enc -aes-256-cbc -salt \
              -in ${FILE}.dec -out ${FILE%.[^.]*} \
              -pass env:WM_SALT
      ;;
    -d )
      openssl enc -d -aes-256-cbc -salt \
              -in ${FILE%.[^.]*} -out ${FILE}.dec \
              -pass env:WM_SALT
      ;;
    * )
      echo "$0 -[d|e] file
        -d decrypt file
        -e encrypt file
        "
esac
